export default function Head() {
  return (
    <>
      {/*  TODO: LEAVE IT DYNAMICALLY */}
      <title>Search for a restaurant</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
